In [26]:
import torch

In [27]:
A = torch.arange(48).reshape(8, -1)
A

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]])

In [28]:
A.T.T == A

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])

In [29]:
B = torch.rand(48).reshape(8, -1)
B

tensor([[0.4076, 0.7594, 0.2345, 0.8476, 0.7913, 0.0828],
        [0.7467, 0.1182, 0.4262, 0.3880, 0.1534, 0.3227],
        [0.3210, 0.5764, 0.4245, 0.0894, 0.1264, 0.9848],
        [0.7043, 0.6285, 0.2926, 0.5963, 0.4823, 0.3762],
        [0.4914, 0.6009, 0.0836, 0.3286, 0.9189, 0.8862],
        [0.6447, 0.9446, 0.9093, 0.1350, 0.3273, 0.2669],
        [0.1459, 0.4069, 0.6219, 0.6807, 0.8354, 0.0504],
        [0.6020, 0.9169, 0.5168, 0.3125, 0.5540, 0.7112]])

In [30]:
A.T + B.T == (A + B).T

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [31]:
C = torch.arange(16).reshape(4, -1)
C, C + C.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([[ 0,  5, 10, 15],
         [ 5, 10, 15, 20],
         [10, 15, 20, 25],
         [15, 20, 25, 30]]))

In [32]:
D = torch.arange(24).reshape(2, 3, 4)
D, len(D)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2)

In [36]:
A / A.sum(axis=1, keepdim=True)

tensor([[0.0000, 0.0667, 0.1333, 0.2000, 0.2667, 0.3333],
        [0.1176, 0.1373, 0.1569, 0.1765, 0.1961, 0.2157],
        [0.1379, 0.1494, 0.1609, 0.1724, 0.1839, 0.1954],
        [0.1463, 0.1545, 0.1626, 0.1707, 0.1789, 0.1870],
        [0.1509, 0.1572, 0.1635, 0.1698, 0.1761, 0.1824],
        [0.1538, 0.1590, 0.1641, 0.1692, 0.1744, 0.1795],
        [0.1558, 0.1602, 0.1645, 0.1688, 0.1732, 0.1775],
        [0.1573, 0.1610, 0.1648, 0.1685, 0.1723, 0.1760]])